### ISSUE TITLE
Vals cleansing in SongBook filtering

### ISSUE THREAD

**Issue by o-Mateo-o** [akobartek/MFTau_App#1]
Dunno if you had this idea before but what makes me sick while searching is that **commas & non-ascii chars matter**. My request is to somehow alter the serching engine to find the song - lets say _'Eloelo, luźna guma'_ - even when typing either

- _'Eloelo, luzna guma'_ or
- _'Eloelo luźna guma'_.

I've quickly found some workaround using `java.text.Normalizer`. It is not very elegant but I just post it there.

Around the line `79` and `86` of `/app/src/main/java/pl/mftau/mftau/view/adapters/SongBookSearchAdapter.kt` I would replace the current lines with sth like this:

```kotlin
val re = Regex("[^A-Za-z ]")
val searchQuery = Normalizer.normalize(mQuery, Normalizer.Form.NFD).replace(re, "").lowercase()
// this should decompose non-asci chars and then cleanse their suffixes, along with the commas, numbers etc

// .... and then in the loop

val title = song.title
val text = song.text
if (Normalizer.normalize(title, Normalizer.Form.NFD).replace(re, "").lowercase().contains(searchQuery) ||  // and `replace` there
    Normalizer.normalize(text, Normalizer.Form.NFD).replace(re, "").lowercase().contains(searchQuery) // and there
) filteredList.add(Triple(title, text, index))


```

Hope it would not destroy the logic but I'm totaly non-kotlinic + haven't deeply studied the project 🙃

**Comment by akobartek** [comment]
Hey, I have plans to rewrite the whole application in the next months to include new Android UI approach, so it will be multiplatform ready to make from there. Thanks for the feedback, I'm not perfectly happy about current searching in the song book, so in the new app it will be improved - thanks for the idea!

**Comment by akobartek** [comment]
Hello again @o-Mateo-o , I just finished songs searching feature in the new song book and I used your suggestions, hope it will be better from now ;)
[https://github.com/akobartek/MFTau_App/commit/0fdbc52b5bd10c7af23b55f57304a94dc62fb6ed](Commit)
